<a href="https://colab.research.google.com/github/sandhya537/numpy/blob/main/numpy_methods_practicing_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##----- min() method -----##

import numpy as np
a=[[20,40,30],[45,56,67]]
b=[[45,34,46],[46,78,56]]
c=np.array(a)
d=np.array(b)
print("output is :")
print()
print(np.min(c))
print(np.min(d))

output is :

20
34


In [ ]:
import numpy as np
data=[[20,40,30],[45,56,67]]
sales=[[45,34,46],[46,78,56]]
c=np.array(data)
d=np.array(sales)
print("output is :")
print()
print(np.max(c))
print(np.max(d))

output is :

67
78


In [ ]:
import numpy as np
data=[[20,40,30],[45,56,67]]
sales=[[45,34,46],[46,78,56]]
c=np.array(data)
d=np.array(sales)
print("output is :")
print()
print(np.sum(c))
print(np.sum(d))
result=np.sum([c,d])
print(result)

output is :

258
305
563


In [1]:
##------- zeros and ones -----------------------------------------------------------

import numpy as np
b=np.zeros((2,3),int)
print("output is :")
print()
print(b)

import numpy as np
a=np.ones((2,3),int)
print("output is :")
print()
print(a)






output is :

[[0 0 0]
 [0 0 0]]
output is :

[[1 1 1]
 [1 1 1]]


In [2]:
##---------- arange() ---------------------------------------------------

import numpy as np
a=np.arange(0,20,2)
print("output is :")
print()
print(a)

output is :

[ 0  2  4  6  8 10 12 14 16 18]


In [4]:
##-------------linspace()-----------------------------------------------------------

import numpy as np
a=np.linspace(0,1,5)
print("output is:")
print
print(a)

output is:
[0.   0.25 0.5  0.75 1.  ]


In [5]:
###-----------full()---------------------------------------------------------------

import numpy as np
a=np.full((2,3),6)
print("output is :")
print()
print(a)


output is :

[[6 6 6]
 [6 6 6]]


In [14]:
###--------eye()-------------------------------------------------------------

import numpy as np
a=np.eye(2)
print("output is :")
print()
print(a)

output is :

[[1. 0.]
 [0. 1.]]


In [15]:
##------------tranpose(),reshape()-------------------------------------------

import numpy as np
a=np.array([[3,4,2],[4,5,6]])
print("output is:")
print(a)
print()
print("reshape :",a.reshape((6,1)))
print()
print("transpose :",np.transpose(a))

output is:
[[3 4 2]
 [4 5 6]]

reshape : [[3]
 [4]
 [2]
 [4]
 [5]
 [6]]

transpose : [[3 4]
 [4 5]
 [2 6]]


In [16]:
##----------astype()--------------------------------------------------------

import numpy as np
a=np.array([[3.2,4,2.3],[4.8,5.8,6]])
b=np.array(a.astype(int))
print("output is :")
print()
print(a)
print()
print(b)

output is :

[[3.2 4.  2.3]
 [4.8 5.8 6. ]]

[[3 4 2]
 [4 5 6]]


In [18]:
##----------------using index ---------------------------------------------------

import numpy as np
a=np.array([3.2,4,2.3])
d=np.array(a[2])
print("output is :")
print()
print(a)
print()
print("using indexing :",d)

output is :

[3.2 4.  2.3]

using indexing : 2.3


In [20]:
##------------------slicing indexing-, fancy indexing-------------------------------------------

import numpy as np
a=np.array([[1,2,3],[5,6,7],[8,9,10]])
print("output is :")
print(a)
print( "slicing :",a[:,2:3])

import numpy as np
a=np.array([[1,2,3],[5,6,7]])
print()
print("output is :")
print(a)
print("slicing :",a[:,0:1])

import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print()
print("output is :")
print(a)
print("fancy indexing :",a[[3,4,6]])


output is :
[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]
slicing : [[ 3]
 [ 7]
 [10]]

output is :
[[1 2 3]
 [5 6 7]]
slicing : [[1]
 [5]]

output is :
[1 2 3 4 5 6 7 8 9]
fancy indexing : [4 5 7]


In [22]:
##--------------mask()--------------------------------------------------------

import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("output is :")
print(a)
print()
mask=a>7
print("mask :",a[mask])

output is :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

mask : [ 8  9 10 11 12]


In [26]:
##----------------append(),insert()-------------------------------------------------
              ##-delete()---------

import numpy as np
a=np.array([1,2,3,4,5])
b=np.append(a,6)
c=np.insert(a,2,7)
d=np.insert(b,2,7)
print("output is :")
print(a)
print()
print("append :",b)
print()
print("output is :")
print(a)
print("insert :",c)
print("insert :",d)
import numpy as np
a=np.array([5,8,1,7])
b=np.delete(a,1)
print()
print("output is :")
print(a)
print("delete :",b)
import numpy as np
a=np.array([[1,2,3],[5,6,7]])
b=np.delete(a,2,axis=1)
print("delete :",b)

output is :
[1 2 3 4 5]

append : [1 2 3 4 5 6]

output is :
[1 2 3 4 5]
insert : [1 2 7 3 4 5]
insert : [1 2 7 3 4 5 6]

output is :
[5 8 1 7]
delete : [5 1 7]
delete : [[1 2]
 [5 6]]


In [30]:
##------vstack(),hstack()-----------------------------------------------------------

import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[14,15,16],[7,8,9]])
c=np.vstack((a,b))
d=np.hstack((a,b))
print("output is :")
print(a)
print(b)
print()
print("vstack :",c)
print()
print("output is :")
print(a)
print(b)
print()
print("hstack :",d)


output is :
[[1 2 3]
 [4 5 6]]
[[14 15 16]
 [ 7  8  9]]

vstack : [[ 1  2  3]
 [ 4  5  6]
 [14 15 16]
 [ 7  8  9]]

output is :
[[1 2 3]
 [4 5 6]]
[[14 15 16]
 [ 7  8  9]]

hstack : [[ 1  2  3 14 15 16]
 [ 4  5  6  7  8  9]]


In [32]:
##-------spilt()--------------------------------------------------------------------

import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=np.split(a,4)
print("output is :")
print(a)
print()
print("split :",b)

import numpy as np
a=np.array([1,2,3,4,5,6])
c=np.array([7,8,9,10,11,12])
b=np.mean([a,c])
print()
print("output is :")
print(a)
print(c)
print("mean :",b)

output is :
[ 1  2  3  4  5  6  7  8  9 10 11 12]

split : [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

output is :
[1 2 3 4 5 6]
[ 7  8  9 10 11 12]
mean : 6.5


In [33]:
###-------------copy() ,view()------------------------------------------------------

import numpy as np
a=np.array([1,2,3,4,5,6])
c=np.array([7,8,9,10,11,12])
b=np.copy([a,c])
b[1,0]=20
print("output is:")
print([a])
print([c])
print()
print("copy :",b)
import numpy as np
a=np.array([1,2,3,4,5,6])
b=a.view()
b[1]=20
print()
print("output is :")
print(a)
print("view :",b)

output is:
[array([1, 2, 3, 4, 5, 6])]
[array([ 7,  8,  9, 10, 11, 12])]

copy : [[ 1  2  3  4  5  6]
 [20  8  9 10 11 12]]

output is :
[ 1 20  3  4  5  6]
view : [ 1 20  3  4  5  6]
