<a href="https://colab.research.google.com/github/sandhya537/numpy/blob/main/numpy_methods_practicing_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
###------ sort() method -----##
##---example 1

import numpy as np
data=np.array([[56,44,14],[65,97,78]])
print("output is:")
print(data)
data.sort()
print()
print("sorted data:",data)

output is:
[[56 44 14]
 [65 97 78]]

sorted data: [[14 44 56]
 [65 78 97]]


In [ ]:
##---example 2
import numpy as np
data=np.array([[30,20,40],[60,10,50]])
print("output is:")
print(data)
print()
print("sorted data:",np.sort(data))


output is:
[[30 20 40]
 [60 10 50]]

sorted data: [[20 30 40]
 [10 50 60]]


In [ ]:
##------flatten() method -----##
##---example 1

import numpy as np
data=np.array([[56,44,14],[65,97,78]])
print("output is:")
print(data)
print()
print("flatten data:",data.flatten())

output is:
[[56 44 14]
 [65 97 78]]

flatten data: [56 44 14 65 97 78]


In [ ]:
##---example 2
import numpy as np
data=np.array([[11,55,33],[66,99,77]])
print("output is:")
print(data)
print()
print("flatten data:",data.flatten())


output is:
[[11 55 33]
 [66 99 77]]

flatten data: [11 55 33 66 99 77]


In [ ]:
##-----adding value to array ----##
##---example 1

import numpy as np
data=np.array([[30,20,40],[60,10,50]])
print("output is:")
print(data)
print()
print("adding to data:",data+4)


output is:
[[30 20 40]
 [60 10 50]]

adding to data: [[34 24 44]
 [64 14 54]]


In [ ]:
##---example 1

import numpy as np
data=np.array([[35,20,45],[60,15,50]])
print("output is:")
print(data)
print()
print("adding to data:",data+5)

output is:
[[35 20 45]
 [60 15 50]]

adding to data: [[40 25 50]
 [65 20 55]]


In [ ]:
##------- diagonal of matrix -----##
## example 1
import numpy as np
matrix=np.array([[11,55,33],[66,99,77],[44,22,88]])
print("output is:")
print(matrix)
print()
print(" matrix diagonal:",matrix.diagonal())

output is:
[[11 55 33]
 [66 99 77]
 [44 22 88]]

 matrix diagonal: [11 99 88]


In [ ]:
## example 2
import numpy as np
matrix=np.array([[10,50,30],[60,90,70],[40,20,80]])
print("output is:")
print(matrix)
print()
print(" matrix diagonal:",matrix.diagonal())

output is:
[[10 50 30]
 [60 90 70]
 [40 20 80]]

 matrix diagonal: [10 90 80]


In [ ]:
##------- trace of matrix -----##
## example 1
import numpy as np
matrix=np.array([[11,55,33],[66,99,77],[44,22,88]])
print("output is:")
print(matrix)
print()
print(" matrix trace:",matrix.trace())

output is:
[[11 55 33]
 [66 99 77]
 [44 22 88]]

 matrix trace: 198


In [ ]:
## example 2

import numpy as np
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("output is:")
print(matrix)
print()
print(" matrix trace:",matrix.trace())

output is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 matrix trace: 15


In [ ]:
##----adding two martces -- -----##
## TYPE :1-----USING ADD() METHOD-
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[11,22,33],[34,45,65],[67,87,97]])
print("A=",A)
print()
print("B=",B)
print()
print(" using add() A+B=",np.add(A,B))




A= [[1 2 3]
 [4 5 6]
 [7 8 9]]

B= [[11 22 33]
 [34 45 65]
 [67 87 97]]

 using add() A+B= [[ 12  24  36]
 [ 38  50  71]
 [ 74  95 106]]


In [ ]:
## TYPE :2-----USING "+" --

A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[11,22,33],[34,45,65],[67,87,97]])
print("A=",A)
print()
print("B=",B)
print()
print(" using '+' A+B=",(A+B))



A= [[1 2 3]
 [4 5 6]
 [7 8 9]]

B= [[11 22 33]
 [34 45 65]
 [67 87 97]]

 using '+' A+B= [[ 12  24  36]
 [ 38  50  71]
 [ 74  95 106]]


In [ ]:
##----subtracting two martces -- -----##
## TYPE :1-----USING subtract() METHOD--

A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[11,22,33],[34,45,65],[67,87,97]])
print("A=",A)
print()
print("B=",B)
print()
print(" using subtract() A-B=",np.subtract(A,B))



A= [[1 2 3]
 [4 5 6]
 [7 8 9]]

B= [[11 22 33]
 [34 45 65]
 [67 87 97]]

 using subtract() A-B= [[-10 -20 -30]
 [-30 -40 -59]
 [-60 -79 -88]]


In [ ]:
## TYPE :2-----USING " - " --

A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[11,22,33],[34,45,65],[67,87,97]])
print("A=",A)
print()
print("B=",B)
print()
print(" using '-' A-B=",(A-B))


A= [[1 2 3]
 [4 5 6]
 [7 8 9]]

B= [[11 22 33]
 [34 45 65]
 [67 87 97]]

 using '-' A-B= [[-10 -20 -30]
 [-30 -40 -59]
 [-60 -79 -88]]
